"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Brain, AudioLines, Crosshair, Flag, Waypoints, Timer, BookOpen, Check, Coffee, Maximize2, Orbit, Pause, Play, Rocket, RotateCcw, Shield, Sparkles, Star, Volume2, VolumeX, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
import { W, H, rounds, createGame, step, activateBoost, objective, retryGame, roundRules, recordQuizAnswer, finishQuiz, type Game } from '@/lib/arcade';

import { NeuroRound } from '@/components/neuro-round';
import { neuroscience } from '@/lib/neuroscience';
import { drawChallenges } from '@/lib/arcade-render';

type Mode = 'failed'|'briefing'|'intro'|'countdown'|'playing'|'paused'|'round'|'finish';
type Hud = {score:number;collected:number;cooldown:number;boost:boolean;combo:number;elapsed:number;objective:string;timeLeft:number;roundBumps:number;attempt:number};
const initialHud:Hud={score:0,collected:0,cooldown:0,boost:false,combo:0,elapsed:0,objective:'',timeLeft:60,roundBumps:0,attempt:1};
const collectIcons=[Coffee,BookOpen,Star,Rocket,Timer,Sparkles,Waypoints,Flag,Brain];
const directions=[{name:'up',Icon:ArrowUp,x:0,y:-1},{name:'left',Icon:ArrowLeft,x:-1,y:0},{name:'down',Icon:ArrowDown,x:0,y:1},{name:'right',Icon:ArrowRight,x:1,y:0}];
export default function Home(){
  const [mode,setMode]=useState<Mode>('intro'),[round,setRound]=useState(0),[count,setCount]=useState(3),[hud,setHud]=useState<Hud>(initialHud),[sound,setSound]=useState(false),[ready,setReady]=useState(false),[feedback,setFeedback]=useState(''),[help,setHelp]=useState(false);
  const overlayAction=useRef<HTMLButtonElement>(null);
  const helpRef=useRef(false);helpRef.current=help;
  const canvas=useRef<HTMLCanvasElement>(null),shell=useRef<HTMLDivElement>(null),game=useRef<Game>(createGame()),modeRef=useRef<Mode>('intro'),keys=useRef(new Set<string>()),pointer=useRef<{x:number;y:number}|undefined>(undefined),pad=useRef(new Map<number,{x:number;y:number}>()),images=useRef<HTMLImageElement[]>([]),raf=useRef(0),soundRef=useRef(false),audio=useRef<AudioContext|null>(null),lastHud=useRef(0),feedbackTimer=useRef<ReturnType<typeof setTimeout>|null>(null),countdownTimer=useRef<ReturnType<typeof setInterval>|null>(null),finishHeading=useRef<HTMLHeadingElement>(null);
  const setScreen=useCallback((next:Mode)=>{modeRef.current=next;setMode(next);keys.current.clear();pad.current.clear();pointer.current=undefined;},[]);
  const tone=useCallback((kind:'pickup'|'bump'|'boost'|'complete'|'failed')=>{if(!soundRef.current)return;try{const ctx=audio.current??(audio.current=new AudioContext());if(ctx.state==='suspended')void ctx.resume();const o=ctx.createOscillator(),v=ctx.createGain();o.connect(v);v.connect(ctx.destination);o.type='sine';const f={pickup:740,bump:130,boost:260,complete:990,failed:160}[kind];o.frequency.setValueAtTime(f,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='boost'?700:Math.max(80,f*.75),ctx.currentTime+.15);v.gain.setValueAtTime(.045,ctx.currentTime);v.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);o.start();o.stop(ctx.currentTime+.22);}catch{}},[]);
  const say=useCallback((text:string)=>{setFeedback(text);if(feedbackTimer.current)clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>setFeedback(''),1500);},[]);
  const updateHud=useCallback(()=>{const g=game.current;setHud({score:g.score,collected:g.collected,cooldown:g.cooldown,boost:g.boost>0,combo:g.combo,elapsed:g.elapsed,objective:objective(g),timeLeft:Math.max(0,(rounds[g.round].timeLimit??0)-g.time),roundBumps:g.roundBumps,attempt:g.attempt});},[]);
  const boost=useCallback(()=>{if(modeRef.current==='playing'&&activateBoost(game.current)){tone('boost');say('Murad: optimal.');updateHud();}},[tone,say,updateHud]);
  const pause=useCallback(()=>{if(modeRef.current==='playing')setScreen('paused');else if(modeRef.current==='paused'){setScreen('playing');if(rounds[game.current.round].kind!=='quiz')canvas.current?.focus({preventScroll:true});}},[setScreen]);
  const begin=useCallback((index=0,replay=false)=>{if(countdownTimer.current)clearInterval(countdownTimer.current);game.current=createGame(index,index===0||replay?undefined:game.current);setRound(index);setFeedback('');updateHud();setScreen('briefing');},[setScreen,updateHud]);
  const launch=useCallback(()=>{if(rounds[game.current.round].kind==='quiz'){setScreen('playing');return;}setCount(3);setScreen('countdown');let n=3;countdownTimer.current=setInterval(()=>{n--;if(n>0)setCount(n);else{if(countdownTimer.current)clearInterval(countdownTimer.current);countdownTimer.current=null;setScreen('playing');canvas.current?.focus({preventScroll:true});}},650);},[setScreen]);
  const retry=useCallback(()=>{if(modeRef.current!=='failed')return;game.current=retryGame(game.current);setFeedback('');updateHud();setScreen('briefing');},[setScreen,updateHud]);
  const answer=useCallback((index:number,correct:boolean)=>{if(modeRef.current!=='playing')return false;const accepted=recordQuizAnswer(game.current,index,correct);if(accepted){tone(correct?'pickup':'bump');updateHud();}return accepted;},[tone,updateHud]);
  const completeQuiz=useCallback(()=>{if(modeRef.current!=='playing'||!finishQuiz(game.current))return;updateHud();tone(game.current.complete?'complete':'failed');setScreen(game.current.complete?'round':'failed');},[tone,updateHud,setScreen]);
  useEffect(()=>{let alive=true;const icons=[<Coffee key="coffee" size={36} color="#ffc287" strokeWidth={2}/>,<BookOpen key="book" size={36} color="#b6a5ff" strokeWidth={2}/>,<Star key="star" size={36} color="#8aeadb" fill="#8aeadb22" strokeWidth={2}/>,<Rocket key="ship" size={52} color="#f0fbff" fill="#96e9da33" strokeWidth={1.6}/>,<Timer key="gate" size={36} color="#f6afce"/>,<Sparkles key="comet" size={36} color="#ffd88b"/>,<Waypoints key="route" size={36} color="#a9c8ff"/>,<Flag key="dock" size={36} color="#8aeadb"/>];Promise.all(icons.map(icon=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(renderToStaticMarkup(icon));}))).then(loaded=>{if(alive){images.current=loaded;setReady(true);}}).catch(()=>{if(alive)setReady(true);});return()=>{alive=false;};},[]);
  useEffect(()=>{soundRef.current=sound;},[sound]);
  useEffect(()=>{if(mode==='finish')finishHeading.current?.focus({preventScroll:true});else if(mode==='round'||mode==='paused'||mode==='briefing'||mode==='failed')overlayAction.current?.focus({preventScroll:true});},[mode]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.defaultPrevented||helpRef.current)return;if(e.repeat&&[' ','Escape','p','P'].includes(e.key))return;if(['Escape','p','P'].includes(e.key)){if(modeRef.current==='playing'||modeRef.current==='paused'){e.preventDefault();pause();}return;}if(modeRef.current!=='playing'||rounds[game.current.round].kind==='quiz')return;const key=e.key.toLowerCase();if(key===' '&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();boost();}if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){e.preventDefault();keys.current.add(key);pointer.current=undefined;}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();pad.current.clear();pointer.current=undefined;if(modeRef.current==='playing')setScreen('paused');if(modeRef.current==='countdown'){if(countdownTimer.current)clearInterval(countdownTimer.current);countdownTimer.current=null;setScreen('paused');}};const visibility=()=>{if(document.hidden)blur();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);};},[pause,boost,setScreen]);
  useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let prev=0;const resize=()=>{const dpr=Math.min(window.devicePixelRatio||1,2);el.width=W*dpr;el.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);};resize();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const draw=(now:number)=>{const dt=prev?Math.min((now-prev)/1000,.04):0;prev=now;const g=game.current;
      if(modeRef.current==='playing'){const k=keys.current;let dx=(k.has('arrowright')||k.has('d')?1:0)-(k.has('arrowleft')||k.has('a')?1:0),dy=(k.has('arrowdown')||k.has('s')?1:0)-(k.has('arrowup')||k.has('w')?1:0);for(const p of pad.current.values()){dx+=p.x;dy+=p.y;}const events=step(g,{dx,dy,target:pointer.current},dt);for(const event of events){tone(event);if(event==='pickup')say(g.collected%2?'Rose: neat.':'Murad: amazing.');if(event==='bump')say(`${g.roundBumps} / 3 bumps. Easy does it.`);if(event==='failed'){updateHud();setScreen('failed');}if(event==='complete'){updateHud();setScreen('round');}}if(now-lastHud.current>90){updateHud();lastHud.current=now;}}
      ctx.clearRect(0,0,W,H);const time=reduced?0:now/1000;
      for(let i=0;i<24;i++){const x=(i*149+23)%W,y=(i*83+30)%H;ctx.globalAlpha=.13+.1*Math.sin(time*.8+i);ctx.fillStyle='#c1d9ef';ctx.beginPath();ctx.arc(x,y,i%4===0?1.7:1,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
      if(modeRef.current==='intro'){ctx.save();ctx.translate(W/2,H*.40);ctx.rotate(-Math.PI/4);if(images.current[3])ctx.drawImage(images.current[3],-54,-54,108,108);ctx.restore();raf.current=requestAnimationFrame(draw);return;}
      for(const h of g.hazards){ctx.save();ctx.translate(h.x,h.y);ctx.rotate(time*.5);ctx.strokeStyle='#ff9b82';ctx.fillStyle='#ff795514';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-h.radius,-h.radius,h.radius*2,h.radius*2,6);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-6,-6);ctx.lineTo(6,6);ctx.moveTo(6,-6);ctx.lineTo(-6,6);ctx.stroke();ctx.restore();}
      drawChallenges(ctx,g,images.current,time);
      if(g.boost>0){ctx.strokeStyle='#8aeadb55';ctx.lineWidth=1.5;ctx.setLineDash([5,8]);ctx.beginPath();ctx.arc(g.x,g.y,160,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8aeadb0d';ctx.fill();ctx.strokeStyle='#8aeadb';ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,g.y,39,0,Math.PI*2);ctx.stroke();}
      ctx.save();ctx.translate(g.x,g.y);ctx.rotate(g.angle);ctx.globalAlpha=g.immune>0&&g.boost<=0?.65:1;if(!reduced){ctx.fillStyle=g.boost>0?'#8aeadb':'#c8b5ff';ctx.beginPath();ctx.moveTo(-7,18);ctx.lineTo(0,28+(g.boost>0?25:6)+Math.sin(time*25)*4);ctx.lineTo(7,18);ctx.fill();}ctx.rotate(-Math.PI/4);if(images.current[3])ctx.drawImage(images.current[3],-27,-27,54,54);else{ctx.fillStyle='#f2f8ff';ctx.beginPath();ctx.moveTo(0,-23);ctx.lineTo(18,20);ctx.lineTo(-18,20);ctx.fill();}ctx.restore();
      if(!reduced)for(const p of g.particles){ctx.globalAlpha=Math.max(0,p.life/.65);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;raf.current=requestAnimationFrame(draw);
    };raf.current=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf.current);},[ready,say,tone,updateHud,setScreen]);
  useEffect(()=>()=>{if(feedbackTimer.current)clearTimeout(feedbackTimer.current);if(countdownTimer.current)clearInterval(countdownTimer.current);void audio.current?.close();},[]);
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_game_progress',title:'Read game progress',description:'Read the visible round, score, pickup count, and whether the game is paused. Does not control the ship or skip rounds.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No arguments accepted.');const g=game.current;return {screen:modeRef.current,round:g.round+1,score:g.score,pickups:g.collected,goal:rounds[g.round].goal};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
  const track=(e:React.PointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-rect.left)/rect.width*W,y:(e.clientY-rect.top)/rect.height*H};};
  const isQuiz=rounds[round].kind==='quiz',active=mode==='playing'&&!isQuiz, showControls=!['intro','finish'].includes(mode),RoundIcon=collectIcons[rounds[round].icon];
  return <Dialog open={help} onOpenChange={setHelp}><main className="arcade-shell" ref={shell}>
    <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();if(modeRef.current==='playing')pause();}} aria-label="Neat and Optimal"><Orbit aria-hidden="true"/><span>neat<span className="amp">&</span>optimal<span className="brand-dot">.</span></span></a><div className="top-actions"><span className="two-player"><span/> TWO PLAYERS. ONE SHIP.</span><Button variant="ghost" className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{const next=!sound;soundRef.current=next;setSound(next);if(next)tone('pickup');}}>{sound?<Volume2/>:<VolumeX/>}</Button><DialogTrigger asChild><Button variant="ghost" className="icon-button" aria-label="How to play" onClick={()=>{if(modeRef.current==='countdown'){if(countdownTimer.current)clearInterval(countdownTimer.current);countdownTimer.current=null;setScreen('paused');}else if(modeRef.current==='playing')pause();}}>?</Button></DialogTrigger></div></header>
    <section className={`game-layout ${mode==='intro'?'on-intro':''} ${mode==='finish'?'on-finish':''}`}>
      <div className="game-console">
        <div className="console-top"><div className="live-round"><span className="round-icon"><RoundIcon size={17}/></span><span>{mode==='intro'?'THE LITTLE CO-OP':`${String(round+1).padStart(2,'0')} / ${rounds[round].name.toUpperCase()}`}</span></div><div className="console-tools">{showControls&&<><span className="score" aria-label={`Score ${hud.score}`}>{hud.score.toLocaleString()} <small>PTS</small></span><Button variant="ghost" className="icon-button pause-button" aria-label={mode==='paused'?'Resume game':'Pause game'} disabled={!['playing','paused'].includes(mode)} onClick={pause}>{mode==='paused'?<Play/>:<Pause/>}</Button></>}{mode==='intro'&&<span className="tiny-label">01 — {String(rounds.length).padStart(2,'0')}</span>}</div></div>
        {showControls&&<div className="mission-strip"><span>{String(round+1).padStart(2,'0')} / {String(rounds.length).padStart(2,'0')}</span><p>{mode==='briefing'?rounds[round].subtitle:hud.objective}</p></div>}
        {showControls&&!isQuiz&&<div className={`attempt-hud ${hud.timeLeft<=15?'urgent':''}`}><span><Timer size={15}/>{Math.ceil(hud.timeLeft)}s left</span>{rounds[round].maxBumps&&<span>{hud.roundBumps} / 3 bumps</span>}<span>Attempt {hud.attempt}</span></div>}
        <div className="playfield">
          <canvas ref={canvas} aria-hidden={isQuiz} aria-label="Space playfield. Steer using arrow keys, WASD, directional buttons, or tap or drag on the playfield. Follow the round objective shown above. Avoid orange obstacles. Space activates boost." tabIndex={active?0:-1} onPointerDown={e=>{if(!active)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);track(e);}} onPointerMove={e=>{if(active&&e.currentTarget.hasPointerCapture(e.pointerId))track(e);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{pointer.current=undefined;}}/>
          {mode==='intro'&&<div className="intro-overlay"><span className="pill"><Sparkles size={14}/> YOUR EVENING HAS A SIDE QUEST</span><div className="intro-ship-space"/><p className="intro-caption">One ship. Two very good opinions.</p><Button className="play-button" disabled={!ready} onClick={()=>begin()}><Play size={20} fill="currentColor"/>{ready?'Let’s play':'Warming up…'}<ArrowRight size={20}/></Button><span className="game-length">9 rounds · two brains · one team</span></div>}
          {active&&<><div className="pickup-hud"><RoundIcon size={18}/><strong>{hud.collected}<span> / {rounds[round].goal}</span></strong><div className="pickup-pips">{Array.from({length:rounds[round].goal},(_,i)=><i key={i} className={i<hud.collected?'filled':''}/>)}</div></div>{hud.combo>1&&<span className="combo">×{hud.combo} <span>NEAT STREAK</span></span>}<div className={`floating-feedback ${feedback?'visible':''}`} role="status">{feedback}</div></>}
          {mode==='briefing'&&<div className="screen-overlay briefing-overlay"><span className="overline">DETOUR {round+1} OF {rounds.length}</span><RoundIcon className="briefing-icon" size={34} style={{color:rounds[round].color}}/><h2>{rounds[round].name}</h2><p className="briefing-instruction">{rounds[round].instruction}</p><p className="round-rules">{roundRules(rounds[round])}</p><div className="briefing-roles"><p><strong>Rose</strong>{rounds[round].pilot}</p><p><strong>Murad</strong>{rounds[round].boost}</p></div><Button ref={overlayAction} className="play-button" onClick={launch}>Okay, let’s go<ArrowRight size={20}/></Button></div>}
          {isQuiz&&['playing','paused'].includes(mode)&&<NeuroRound key={`${round}:${hud.attempt}`} questions={neuroscience[rounds[round].quiz!]} attempt={hud.attempt} hidden={mode!=='playing'||help} onAnswer={answer} onFinish={completeQuiz}/>}
          {mode==='failed'&&<div className="screen-overlay failed-overlay"><RotateCcw size={34}/><span className="overline">ROUND {round+1} · TRY AGAIN</span><h2>One more go?</h2><p>{game.current.failed}</p><p className="retry-note">{round===0?'A fresh start for this round.':`${round} earlier ${round===1?'round stays':'rounds stay'} completed.`} This attempt’s points reset when you retry.</p><Button ref={overlayAction} className="play-button" onClick={retry}>Retake this round<RotateCcw size={18}/></Button></div>}
          {mode==='countdown'&&<div className="screen-overlay countdown"><span>ROSE, STEER. MURAD, BOOST.</span><strong key={count}>{count}</strong><p>{rounds[round].name}</p></div>}
          {mode==='paused'&&!help&&<div className="screen-overlay pause-overlay"><Pause size={32}/><h2>Snack break?</h2><p>The universe can wait.</p><Button ref={overlayAction} className="play-button" onClick={pause}><Play size={18}/>Keep going</Button><Button variant="ghost" className="quiet-button" onClick={()=>begin(0,true)}><RotateCcw size={16}/>Start fresh</Button></div>}
          {mode==='round'&&<div className="screen-overlay round-overlay"><span className="completion-icon"><Check size={30}/></span><span className="overline">ROUND {round+1} COMPLETE</span><h2>{rounds[round].win}</h2><p>{rounds[round].line}</p>{isQuiz&&<p className="quiz-result">{game.current.quizCorrect} / 4 correct · passed</p>}<div className="round-score">{hud.score.toLocaleString()} <span>points together</span></div><Button ref={overlayAction} className="play-button" onClick={()=>round===rounds.length-1?setScreen('finish'):begin(round+1)}>{round===rounds.length-1?'We did it':'Next stop'}<ArrowRight size={20}/></Button></div>}
          {mode==='finish'&&<div className="screen-overlay finish-overlay"><div className="finish-stars" aria-hidden="true"><Star/><Sparkles/><Star/></div><span className="overline">NINE ROUNDS. SAME TEAM.</span><h1 ref={finishHeading} tabIndex={-1}>Neat team<span>.</span></h1><p className="finish-lead">Okay, one more thing…</p><p className="handoff">Murad, you’re up.</p><div className="end-stats"><div><strong>{hud.score.toLocaleString()}</strong><span>points together</span></div><div><strong>{rounds.length} / {rounds.length}</strong><span>detours completed</span></div></div><Button variant="ghost" className="quiet-button" onClick={()=>begin(0,true)}><RotateCcw size={16}/>Another round sometime?</Button></div>}
          <DialogContent className="help-dialog" onEscapeKeyDown={e=>{e.preventDefault();e.stopPropagation();setHelp(false);}}><span className="overline">QUICK FLIGHT BRIEFING</span><DialogTitle>You’ve got this.</DialogTitle><DialogDescription>One ship. You’re both in charge.</DialogDescription><p><strong>Rose:</strong> steer with the arrows / WASD, the direction pad, or tap / drag anywhere in space.</p><p><strong>Murad:</strong> hit Space or the BOOST button. It speeds you up, shields you, and pulls in nearby pickups.</p><p>Each stop has its own challenge: collect, chase, connect, time a boost, or land. Finish each flight before its timer runs out. In obstacle rounds, the third bump ends the attempt. Fail a round and retake it; earlier rounds stay completed.</p><p>The two neuroscience rounds are untimed. Get 3 of 4 answers right in each to pass.</p><Button className="play-button" onClick={()=>setHelp(false)}>Got it<Check size={18}/></Button></DialogContent>
        </div>
        {showControls&&!isQuiz&&mode!=='briefing'&&mode!=='failed'&&<div className="control-deck"><div className="steering"><div className="control-label"><span className="player-tag rose-tag">R</span><strong>Rose, steer</strong><small>WASD / ↑↓←→</small></div><div className="dpad" aria-label="Steering controls">{directions.map(d=><button key={d.name} className={`direction direction-${d.name}`} aria-label={`Steer ${d.name}`} disabled={!active} onPointerDown={e=>{if(!active)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointer.current=undefined;pad.current.set(e.pointerId,{x:d.x,y:d.y});}} onPointerUp={e=>{pad.current.delete(e.pointerId);}} onPointerCancel={e=>pad.current.delete(e.pointerId)} onLostPointerCapture={e=>pad.current.delete(e.pointerId)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();pad.current.set(-1,{x:d.x,y:d.y});}}} onKeyUp={()=>pad.current.delete(-1)} onBlur={()=>pad.current.delete(-1)}><d.Icon size={20}/></button>)}</div></div><div className="boost-control"><div className="control-label"><span className="player-tag murad-tag">M</span><strong>Murad, boost</strong><small>SPACE</small></div><Button className={`boost-button ${hud.boost?'boosting':''}`} disabled={!active||hud.cooldown>0} onClick={boost}><Zap size={24} fill="currentColor"/><span>{hud.boost?'AMAZING':hud.cooldown>0?'CHARGING':'BOOST'}<small>{hud.cooldown>0?`${hud.cooldown.toFixed(1)}s`:'Shield + magnet'}</small></span></Button><Progress className="boost-meter" value={(1-hud.cooldown/4.5)*100} aria-label="Boost recharge"/></div></div>}
        <div className="console-bottom"><span><span className="status-light"/>{mode==='intro'?'READY WHEN YOU TWO ARE':active?'SAME SHIP. SAME TEAM.':mode==='finish'?'THE NEXT BIT IS ALL YOU':'NO RUSH'}</span><span>N&O <span className="muted">/</span> CO-OP 01</span></div>
      </div>
      <aside className="side-panel">
        <div className="intro-copy"><span className="overline">A LITTLE GAME FOR US</span><h1>{mode==='finish'?'Pretty':<>Good<br/>company.</>}<br/><span>{mode==='finish'?'amazing.':'Questionable'}{mode!=='finish'&&<><br/>flying.</>}</span></h1><p>{mode==='finish'?'Coffee, books, and getting a little distracted together. Sounds about right.':'A coffee run, a comet chase, and a few questionable detours. Let’s see where we end up.'}</p></div>
        <div className="crew"><div className="crew-person"><span className="avatar rose-avatar">R</span><div><strong>Rose <span>THE PILOT</span></strong><p>“neat”</p></div><span className="role-symbol"><Orbit/></span></div><div className="crew-person"><span className="avatar murad-avatar">M</span><div><strong>Murad <span>THE BOOST</span></strong><p>“amazing” · “optimal”</p></div><span className="role-symbol"><Zap/></span></div></div>
        <div className="route-list"><span className="overline">NINE LITTLE DETOURS</span>{rounds.map((r,i)=>{const Icon=collectIcons[r.icon],done=i<round||mode==='finish'||(i===round&&mode==='round');return <div className={`route-stop ${i===round?'current':''} ${done?'done':''}`} key={r.name}><span className="route-stop-icon">{done?<Check size={17}/>:<Icon size={17}/>}</span><span>{r.name}</span><small>{String(i+1).padStart(2,'0')}</small></div>;})}</div>
        <div className="co-op-note"><Shield size={18}/><p>One does the steering.<br/>One makes questionable boost decisions.</p></div>
      </aside>
    </section>
    <footer className="site-footer"><span>Made for Rose. <span className="footer-dash">Quite intentionally.</span></span><span>Best played shoulder to shoulder <Sparkles size={13}/></span></footer>
  </main></Dialog>;
}
