export type Question = {id:string;question:string;options:string[];correct:number;explanation:string;feedback:string[];hint:string;source:string;sourceLabel:string};
export const neuroscience:Record<'wiring'|'brain',Question[]>={
  wiring:[
    {id:'dendrites',question:'Which branching parts of a typical neuron receive many incoming messages?',options:['Axon terminals','Dendrites','Myelin sheaths','Nuclei'],correct:1,explanation:'Dendrites are branching extensions that receive signals from other cells. Those incoming signals help determine the neuron’s activity.',feedback:['Axon terminals typically release signals to target cells.','Dendrites provide many of a neuron’s receiving branches.','Myelin insulates many axons.','The nucleus holds the cell’s genetic material.'],hint:'Think about the receiving branches of the cell.',source:'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-life-and-death-neuron',sourceLabel:'NINDS · Neurons'},
    {id:'axon',question:'Which part usually carries a neuron’s outgoing electrical signal toward other cells?',options:['Nucleus','Dendrite','Axon','Cell body'],correct:2,explanation:'The axon carries signals away from the cell body toward its terminals, which communicate with target cells.',feedback:['The nucleus houses genetic material.','Dendrites typically receive incoming signals.','The axon carries the outgoing signal.','The cell body supports the cell and integrates incoming signals.'],hint:'Follow the message away from the cell body.',source:'https://www.ncbi.nlm.nih.gov/books/NBK20367/',sourceLabel:'NIH · Information about the Brain'},
    {id:'myelin',question:'What is a key job of myelin around an axon?',options:['Store genetic information','Carry oxygen to neurons','Bind neurotransmitters','Insulate and speed signals'],correct:3,explanation:'Myelin insulates many axons and helps electrical signals travel faster. The signal is regenerated at gaps between myelin segments.',feedback:['Genetic information is stored in DNA.','Blood supplies neurons with oxygen.','Neurotransmitters bind to receptors.','Myelin provides insulation that speeds signal conduction.'],hint:'Think about why an electrical cable might need a covering.',source:'https://www.nih.gov/news-events/news-releases/astrocytes-regulate-signal-speeds-neurons',sourceLabel:'NIH · Signal speeds'},
    {id:'synapse',question:'At a chemical synapse, what carries a message across the gap between cells?',options:['Neurotransmitters','Myelin layers','Axon fibers','Cell nuclei'],correct:0,explanation:'Released neurotransmitter molecules cross the gap and bind to receptors on the receiving cell, influencing its activity.',feedback:['Neurotransmitters are the chemical messengers.','Myelin insulates axons; it does not carry messages across the gap.','Axons conduct signals toward terminals, but do not span this gap.','Cell nuclei do not travel between cells.'],hint:'The word “chemical” is doing useful work here.',source:'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-know-your-brain',sourceLabel:'NINDS · Know Your Brain'},
  ],
  brain:[
    {id:'hippocampus',question:'Which structure is especially important for forming new memories of facts and events?',options:['Hypothalamus','Medulla','Hippocampus','Occipital cortex'],correct:2,explanation:'The hippocampus helps form new memories of facts and experiences. Memory involves a wider network; it is not all stored in one place.',feedback:['The hypothalamus helps regulate functions such as temperature and hunger.','The medulla helps regulate vital functions such as breathing.','The hippocampus is important for forming these new memories.','Occipital cortex is especially involved in visual processing.'],hint:'Its name comes from its seahorse-like shape.',source:'https://nba.uth.tmc.edu/neuroscience/m/s4/chapter07.html',sourceLabel:'UTHealth · Learning and Memory'},
    {id:'cerebellum',question:'Which structure helps coordinate movement and learn practiced movements?',options:['Cerebellum','Hippocampus','Hypothalamus','Olfactory bulb'],correct:0,explanation:'The cerebellum helps coordinate movement and contributes to learning motor skills. It works with other brain regions as movements are refined.',feedback:['The cerebellum contributes to coordination and motor learning.','The hippocampus is important for forming memories of facts and events.','The hypothalamus helps regulate internal bodily conditions.','The olfactory bulb processes information about smell.'],hint:'Think about coordinating a practiced physical skill, such as playing an instrument.',source:'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-know-your-brain',sourceLabel:'NINDS · Know Your Brain'},
    {id:'plasticity',question:'What does neuroplasticity describe?',options:['Faster blood flow','Temporary muscle fatigue','Stronger skull protection','Changes in neural connections'],correct:3,explanation:'Neuroplasticity is the nervous system’s capacity to change its structure, function, or connections in response to experience. Learning can involve changing connections between neurons.',feedback:['Blood flow can change, but that is not what this term describes.','Muscle fatigue is not the definition of neuroplasticity.','The skull’s protection is not the focus of this term.','Changing neural connections is an example of neuroplasticity.'],hint:'Think about how experience can change a network.',source:'https://biotech.ucdavis.edu/blog/neuroplasticity',sourceLabel:'UC Davis · Neuroplasticity'},
    {id:'sleep',question:'How does sleep generally support learning?',options:['Prevents new memories','Helps form lasting memories','Stops all brain activity','Replaces the need to practice'],correct:1,explanation:'Sleep supports learning and long-term memory. Poor or insufficient sleep can make it harder to concentrate and think clearly.',feedback:['Sleep generally supports memory formation.','Sleep helps support lasting memories.','The brain remains active during sleep.','Sleep supports learning, but practice is still useful.'],hint:'The brain continues doing useful work while you rest.',source:'https://www.nhlbi.nih.gov/health/sleep/why-sleep-important',sourceLabel:'NHLBI · Why Sleep Is Important'},
  ],
};
